### ISSUE TITLE
可以支持vercel吗

### ISSUE THREAD

**Issue by JeazW** [zxl20070701/toolbox#2]
## 目前vercel部署报错：
![image](https://github.com/zxl20070701/toolbox/assets/75829171/8f479453-d639-4823-8f59-1fd0e5db7ea2)
vercel也是一个非常好的托管方案，如果大佬还没用过，推荐去看一看，一定会喜欢上的😄

**Comment by zxl20070701** [comment]
可以，我看一下

**Comment by zxl20070701** [comment]
https://vercel.com/zxl20070701-domain/toolbox

![image](https://github.com/zxl20070701/toolbox/assets/112325193/53050678-331c-42d5-baf5-fd12bfd486a8)

**Comment by zxl20070701** [comment]
对提供的功能如果有感觉修改或者希望补充的，可以留言，最近打算有空维护一下，进行一些升级 @JeazW

**Comment by zxl20070701** [comment]
Output 文件夹设置成 docs 


![image](https://github.com/zxl20070701/toolbox/assets/112325193/24da055a-553d-4fd2-ae42-de46c9cdf922)

**Comment by JeazW** [comment]
> 对提供的功能如果有感觉修改或者希望补充的，可以留言，最近打算有空维护一下，进行一些升级 @JeazW

好的好的，感谢大佬对开源社区做出的贡献👍
